# docker-compose.yml

version: '3'

services:
  django:
    container_name: django
    build: ./app
    volumes:
      - static_volume:/opt/app/static/
    expose:
      - "8000"
    env_file:
      - ./app/config/.env


  postgres:
    container_name: postgres
    image: postgres:13-alpine
    volumes:
      - $HOME/postgresql/data:/var/lib/postgresql/data
    env_file:
      - ./app/config/.env

  nginx:
    container_name: nginx
    image: nginx:1.19.2
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./configs/conf.d:/etc/nginx/conf.d:ro
      - ./data:/data/:ro
      - static_volume:/opt/app/static/
      - media_volume:/opt/app/media/
    depends_on:
      - django
    ports:
      - "80:80"
      - "8000:8000"
volumes:
  postgres_data:
  static_volume:
  media_volume:
